### ISSUE TITLE
Dependency Upgrade Policy

### ISSUE THREAD

**Issue by tukib** [comcode-org/hackmud_wiki#35]
### Problem

We do not have a policy for upgrading the dependencies we rely upon.

### Goal

Our goal is to develop a policy that answers:

- How do we propose and assess the need for a dependency upgrade?
- How do we implement and review a dependency upgrade?

### Tasks

- [x] Decide where this policy will be documented.
- [x] Document an assessment procedure:
  - [x] Decide where upgrade assessments should be documented (e.g. PR, issue, project)
  - [x] Identify required information for an upgrade decision
  - [x] Define (or rule out) a measure for perceived importance and/or complexity
- [x] Document a review procedure:
  - [x] Identify required information for implementation and review
  - [x] ~~Define a test plan~~ really just standard review procedure, any strict definition can be done with workflow impl

Several items are out of scope for this issue, but have been acknowledged as potential future work:

- Upgrade workflows and automation
- Regular auditing of dependencies
- Addressing implications of deferring/denying upgrades (e.g. security)

**Comment by tukib** [comment]
For upgrade assessments, I think the policy should provide a specific issue template. Generally if we are proposing an upgrade, we have some idea of the motivation. The issue description might start out with empty sections or TBDs, but this can be fleshed out as the upgrade is assessed. It also documents the proposal clearly without having to read through comments.

The assessment template could require:
- upgrade motivation, categorise into:
  - hard requirements (e.g. security, it *must* be done or addressed in some other way)
  - specific advantages
  - non-specific benefit (e.g. preventing version drift)
- version bumps for itself and related dependencies, whether we already meet them

NPM recommends Semantic Versioning[^1], so it might make sense to fast-track the assessment procedure if no major version bumps are necessary.
- Major: provide some examples of breaking changes to determine how much work the upgrade would cause.
- Minor/patch: if the work leading up to this did not unveil breaking changes, just skip this in the evaluation. If it does break, we should be catching it in the review process and we can backtrack.

As for the review procedure, I think this is pretty much just standard review workflow: open a PR, update dependencies, test with test plan, fix issues and repeat, then merge. I don't think we require any specific information for impl/review per say, but with #34 we may identify things that make sense to document. Docusaurus has provided guidance for a testing workflow[^2], which is essentially:
- ensure site builds
- identify visual regressions[^3]



[^1]: NPM docs on SemVer [About Semantic Versioning](https://docs.npmjs.com/about-semantic-versioning) -
[^2]: Docusaurus workflow suggestion [Upgrading frontend dependencies with confidence](https://docusaurus.io/blog/upgrading-frontend-dependencies-with-confidence-using-visual-regression-testing) -
[^3]: ChatGPT on visual regressions [Detecting Visual Regressions](https://chat.openai.com/share/e98f9954-eea6-4590-8766-8db20067b814) -
