### ISSUE TITLE
The wiki needs a contribution meta-guide

### ISSUE THREAD

**Issue by matr1x-hackmud** [comcode-org/hackmud_wiki#413]
### Problem

Players can play a significant amount of hackmud without ever interacting with the infrastructure that the hackmud wiki uses to add new contributions (GitHub, GH actions, PR etiquette etc.) - we need a guide to 

### Context

We'd be basically doing a "GitHub 101" page (probably for a new meta-guides category):

- [ ] What is git/version control?
- [ ] How does Docusaurus use our markdown?
- [ ] How do I fork the repo?
- [ ] How do I change the content?
- [ ] How do I make a PR?
- [ ] What is this 'CLA'? Why am I signing away my soul?
- [ ] When will my request get merged? What are the criteria for a successful merge?

**Comment by seanmakesgames** [comment]
Thanks @matr1x-hackmud -- @oolu4236
